SistemaClinica/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaClinica.Models
{
    public class Cliente
    {
        [Key]
        public int Id_cliente { get; set; }
        public string Nombre {  get; set; }
        public string Apellidos {  get; set; }
        public string Email {  get; set; }
        [DataType(DataType.Date)]
        public DateTime? Cita {  get; set; }
        public string Telefono {  get; set; }
    }
}

SistemaClinica/Models/ErrorViewModel.cs
using System;

namespace SistemaClinica.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaClinica/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaClinica.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult AboutUs()
        {
            return View();
        }
    }
}

SistemaClinica/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaClinica.Controllers
{
    public class ContactUsController : Controller
    {
        public IActionResult ContactUs()
        {
            return View();
        }
    }
}

SistemaClinica/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SistemaClinica.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaClinica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaClinica/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaClinica.Controllers
{
    public class ServicesController : Controller
    {
        // GET: ServicesController
        public ActionResult Services()
        {
            return View();
        }

    }
}

SistemaClinica/Views/ContactUs/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
}



<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">
                    Contáctenos,<small> estamos para servirle</small>
                </h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">
                                    Nombre
                                </label>
                                <input type="text" class="form-control" id="name" placeholder="Su nombre" required="required" />
                            </div>
                            <div class="form-group">
                                <label for="email">
                                    Correo Electrónico
                                </label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-envelope"></span>
                                    </span>
                                    <input type="email" class="form-control" id="email" placeholder="Ingrese su Correo" required="required" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="subject">
                                    Motivo de su contacto
                                </label>
                                <select id="subject" name="subject" class="form-control" required="required">
                                    <option value="na" selected="">Elija una opción:</option>
                                    <option value="service">Necesita una cita</option>
                                    <option value="suggestions">Realizar una sugerencia</option>
                                    <option value="product">Tiene consultas</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">
                                    Su mensaje
                                </label>
                                <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                          placeholder=""></textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                                Enviar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
                <legend><span class="glyphicon glyphicon-globe"></span> Nuestra Dirección</legend>
                <address>
                    <strong>Montero Smile Art</strong><br>
                    200 mts sur y 150 mts oeste de Torre Universal, <br>
                    edificio Montero Smile Art, <br>
                    Sabana Sur 10108 San José, Costa Rica. <br>
                    <abbr title="Phone">
                        Teléfono:
                    </abbr>
                    40702022
                </address>
                <address>
                    <strong>Nuestro Correo</strong><br>
                    <a href="mailto:#">hola@monterosmileart.com</a>
                </address>
            </form>
        </div>
    </div>
</div>

SistemaClinica/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<br />
<h1>Bienvenido a Montero Smile Art</h1>
<br />
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100 h-25"  src="~/images/2.jpeg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/1.jpeg"  alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/3.jpeg"  alt="Third slide">
        </div>
    </div>
</div>

SistemaClinica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaClinica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div>
                    
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="d-block w-25" src="~/images/4.jpeg" ></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutUs" asp-action="AboutUs">Acerca de nuestra Clínica</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Services">Nuestros Servicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContactUs" asp-action="ContactUs">Contáctenos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Montero Smile Art - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>